export const TYPES = {
	App: Symbol.for("App"),
	PdfNotesService: Symbol.for("PdfNotesService"),
	NoteRepository: Symbol.for("NoteRepository"),
	LinkRepository: Symbol.for("LinkRepository"),
	FileSystem: Symbol.for("FileSystem"),
	StateManager: Symbol.for("StateManager"),
	SubNotesController: Symbol.for("SubNotesController"),
	PdfNoteViewController: Symbol.for("PdfNoteViewController"),
	FileLinkService: Symbol.for("FileLinkService"),
	PdfEventService: Symbol.for("PdfEventService"),
	BrokenLinkModalController: Symbol.for("BrokenLinkModalController"),
	FilePickerModalController: Symbol.for("FilePickerModalController"),
	PdfNoteView: Symbol.for("PdfNoteView"),
	PdfNoteViewControllerFactory: Symbol.for("PdfNoteViewControllerFactory"),
		PdfNoteViewFactory: Symbol.for("PdfNoteViewFactory"),
	FilePickerModalFactory: Symbol.for("FilePickerModalFactory"),
	BrokenLinkModalFactory: Symbol.for("BrokenLinkModalFactory"),
};
